// Code generated by protoc-gen-go-grpc_server. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc_server v1.5.1
// - protoc             v6.32.0
// source: api/order_v1/order.proto

package order_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc_server package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderServiceV1_CreateOrder_FullMethodName = "/order.OrderServiceV1/CreateOrder"
	OrderServiceV1_GetOrder_FullMethodName    = "/order.OrderServiceV1/GetOrder"
)

// OrderServiceV1Client is the client API for OrderServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceV1Client interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
}

type orderServiceV1Client struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceV1Client(cc grpc.ClientConnInterface) OrderServiceV1Client {
	return &orderServiceV1Client{cc}
}

func (c *orderServiceV1Client) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, OrderServiceV1_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceV1Client) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, OrderServiceV1_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceV1Server is the server API for OrderServiceV1 service.
// All implementations must embed UnimplementedOrderServiceV1Server
// for forward compatibility.
type OrderServiceV1Server interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	mustEmbedUnimplementedOrderServiceV1Server()
}

// UnimplementedOrderServiceV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceV1Server struct{}

func (UnimplementedOrderServiceV1Server) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderServiceV1Server) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrderServiceV1Server) mustEmbedUnimplementedOrderServiceV1Server() {}
func (UnimplementedOrderServiceV1Server) testEmbeddedByValue()                        {}

// UnsafeOrderServiceV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceV1Server will
// result in compilation errors.
type UnsafeOrderServiceV1Server interface {
	mustEmbedUnimplementedOrderServiceV1Server()
}

func RegisterOrderServiceV1Server(s grpc.ServiceRegistrar, srv OrderServiceV1Server) {
	// If the following call pancis, it indicates UnimplementedOrderServiceV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderServiceV1_ServiceDesc, srv)
}

func _OrderServiceV1_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceV1Server).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderServiceV1_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceV1Server).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderServiceV1_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceV1Server).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderServiceV1_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceV1Server).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderServiceV1_ServiceDesc is the grpc.ServiceDesc for OrderServiceV1 service.
// It's only intended for direct use with grpc_server.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderServiceV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderServiceV1",
	HandlerType: (*OrderServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderServiceV1_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _OrderServiceV1_GetOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/order_v1/order.proto",
}
